after_success:
  - pip install coveralls
  - coveralls

stages:
  - test
  - name: deploy
    if:
      tag IS present AND repo = brainglobe/brainatlas-api


jobs:
  include:
    - stage: test
      name: "Ubuntu Xenial python 3.6"
      language: python
      os: linux
      env: MINICONDA_URL=http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
      dist: xenial
      python: 3.7
      before_install: source travis/install_unix.sh
      script: bash travis/test.sh

    - stage: test
      name: "Ubuntu Xenial python 3.7"
      language: python
      os: linux
      env: MINICONDA_URL=http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
      dist: xenial
      python: 3.7
      before_install: source travis/install_unix.sh
      script: bash travis/test.sh

    - stage: test
      name: "Ubuntu Xenial python 3.8"
      language: python
      os: linux
      env: MINICONDA_URL=http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
      dist: xenial
      python: 3.8
      before_install: source travis/install_unix.sh
      script: bash travis/test.sh

    - stage: test
      name: "Ubuntu Xenial python 3.8"
      language: python
      os: linux
      env: MINICONDA_URL=http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
      dist: xenial
      python: 3.8
      before_install: source travis/install_unix.sh
      script: bash travis/test.sh

    - stage: test
      name: "Ubuntu Bionic python 3.7"
      language: python
      os: linux
      env: MINICONDA_URL=http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
      dist: bionic
      python: 3.6
      before_install: source travis/install_unix.sh
      script: bash travis/test.sh

    - stage: test
      name: "Windows Python 3.7"
      language: shell
      env: TRAVIS_PYTHON_VERSION=3.7
      os: windows
      before_install: source travis/install_windows.sh
      script: bash travis/test.sh

    - stage: test
      name: "macOS Python 3.7"
      os: osx
      language: shell
      env:
      - TRAVIS_PYTHON_VERSION=3.7
      - MINICONDA_URL=https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
      before_install: source travis/install_unix.sh
      script: bash travis/test.sh
      
    - stage: test
      name: "Ubuntu Xenial python 3.7"
      language: python
      os: linux
      env: MINICONDA_URL=http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
      dist: xenial
      python: 3.7
      before_install: source travis/install_unix.sh
      script: bash travis/lint.sh


    - stage: deploy
      os: bionic
      name: "Deploy Linux"
      language: python
      before_install: source travis/install_unix.sh
      script: bash travis/deploy_linux.sh
notifications:
  email:
    recipients:
    - adam.tyson@ucl.ac.uk
    on_success: change
    on_failure: always

env:
  global:
    - TWINE_USERNAME=__token__
    # TWINE_PASSWORD is set to a PyPI API token in Travis settings